Repository Sysone2ndProject/DDogdog, pull requests merged in 2024-09, with the labels that each got.

#3 [Fix] gradle.build 에러 수정
  settings.gradle
Labels: 버그 처리

#7 [Chore] JSP, Security 의존성 추가 및 프로젝트 구조 설정
  build.gradle
  src/main/java/com/sysone/ddogdog/config/AuthenticattorFilter.java
  src/main/java/com/sysone/ddogdog/customer/auth/controller/AuthController.java
  src/main/java/com/sysone/ddogdog/customer/auth/mapper/AuthMapper.xml
  src/main/java/com/sysone/ddogdog/customer/auth/model/OAuthUser.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/request/requestDTO.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/response/responseDTO.java
  src/main/java/com/sysone/ddogdog/customer/auth/repository/AuthRepository.java
  src/main/java/com/sysone/ddogdog/customer/auth/service/AuthService.java
  src/main/java/com/sysone/ddogdog/customer/common/exception/CommonException.java
  src/main/java/com/sysone/ddogdog/customer/common/util/CommonUtils.java
  src/main/java/com/sysone/ddogdog/owner/auth/controller/AuthController.java
  src/main/java/com/sysone/ddogdog/owner/auth/mapper/AuthMapper.java
  src/main/java/com/sysone/ddogdog/owner/auth/model/request/RequestDTO.java
  src/main/java/com/sysone/ddogdog/owner/auth/model/response/ResponseDTO.java
  src/main/java/com/sysone/ddogdog/owner/auth/repository/AuthRepository.java
  src/main/java/com/sysone/ddogdog/owner/auth/service/AuthService.java
  src/main/java/com/sysone/ddogdog/owner/common/exception/CommonExceptions.java
  src/main/java/com/sysone/ddogdog/owner/common/util/CommonUtils.java
  src/main/resources/application.yml
  src/main/resources/static/customers/css/customer.css
  src/main/resources/static/customers/js/customer.js
  src/main/resources/static/owners/css/owners.css
  src/main/resources/static/owners/js/owners.js
  src/main/webapp/WEB-INF/views/customer/customer.jsp
  src/main/webapp/WEB-INF/views/owner/owner.jsp
Labels: 프로젝트 세팅

#9 [Feature] Owner회원가입 구현
  src/main/java/com/sysone/ddogdog/common/config/AuthenticattorFilter.java
  src/main/java/com/sysone/ddogdog/common/config/Role.java
  src/main/java/com/sysone/ddogdog/common/controller/CommonController.java
  src/main/java/com/sysone/ddogdog/config/AuthenticattorFilter.java
  src/main/java/com/sysone/ddogdog/owner/auth/controller/AuthController.java
  src/main/java/com/sysone/ddogdog/owner/auth/mapper/AuthMapper.java
  src/main/java/com/sysone/ddogdog/owner/auth/model/AuthDTO.java
  src/main/java/com/sysone/ddogdog/owner/auth/model/request/RequestDTO.java
  src/main/java/com/sysone/ddogdog/owner/auth/model/response/ResponseDTO.java
  src/main/java/com/sysone/ddogdog/owner/auth/repository/AuthMapper.java
  src/main/java/com/sysone/ddogdog/owner/auth/repository/AuthRepository.java
  src/main/java/com/sysone/ddogdog/owner/auth/service/AuthService.java
  src/main/java/com/sysone/ddogdog/owner/common/exception/OwnerException.java
  src/main/resources/application.yml
  src/main/resources/mapper/owner/auth.xml
  src/main/resources/static/owners/js/auth.js
  src/main/resources/static/owners/js/main.js
  src/main/resources/static/owners/js/owners.js
  src/main/webapp/WEB-INF/view/owner/main.jsp
  src/main/webapp/WEB-INF/view/owner/signUp.jsp
  src/main/webapp/WEB-INF/views/owner/owner.jsp
Labels: 기능, 백엔드

#11 [Feature] 견주 카카오 OAuth 회원가입 구현
  build.gradle
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/customer/auth/controller/KakaoController.java
  src/main/java/com/sysone/ddogdog/customer/auth/mapper/KakaoMapper.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/AddressCustomerDTO.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/CustomerDTO.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/KakaoProfile.java
  src/main/java/com/sysone/ddogdog/customer/auth/service/KakaoService.java
  src/main/resources/application.yml
  src/main/resources/mapper/customer/auth/kakaoMapper.xml
  src/main/resources/static/customers/images/DDogdogLOGO.png
  src/main/resources/static/customers/images/kakao_login_large_wide.png
  src/main/resources/static/customers/js/location.js
  src/main/webapp/WEB-INF/views/customer/auth/home.jsp
  src/main/webapp/WEB-INF/views/customer/auth/location.jsp
  src/main/webapp/WEB-INF/views/customer/auth/login.jsp
Labels: 기능, 프론트엔드, 백엔드

#14 [Chore]프로젝트 구조 변경
  src/main/java/com/sysone/ddogdog/common/controller/CommonController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/mapper/HotelMapper.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/Hotel.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/HotelVO.java
  src/main/java/com/sysone/ddogdog/customer/hotel/service/HotelService.java
  src/main/resources/mapper/customer/hotel.xml
  src/main/resources/static/css/common/font.css
  src/main/resources/static/css/customers/common.css
  src/main/resources/static/css/customers/footer.css
  src/main/resources/static/css/customers/header.css
  src/main/resources/static/css/customers/index.css
  src/main/resources/static/css/owners/owners.css
  src/main/resources/static/customers/js/customer.js
  src/main/resources/static/font/Hakgyoansim Dunggeunmiso TTF B.ttf
  src/main/resources/static/font/Hakgyoansim Dunggeunmiso TTF R.ttf
  src/main/resources/static/img/DDogdogLOGO.png
  src/main/resources/static/img/check_in.svg
  src/main/resources/static/img/check_out.svg
  src/main/resources/static/img/github_logo.svg
  src/main/resources/static/img/kakao_login_large_wide.png
  src/main/resources/static/img/logo.png
  src/main/resources/static/img/logo_nobg.png
  src/main/resources/static/img/search.svg
  src/main/resources/static/js/customers/location.js
  src/main/resources/static/js/owners/auth.js
  src/main/resources/static/js/owners/main.js
  src/main/resources/static/owners/css/owners.css
  src/main/webapp/WEB-INF/views/customer/component/footer.jsp
  src/main/webapp/WEB-INF/views/customer/component/header.jsp
  src/main/webapp/WEB-INF/views/customer/customer.jsp
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 프로젝트 세팅, 기능, 프론트엔드, 백엔드

#19 [Feature] Owner 로그인 시큐리티 설정 및 구조 변경
  src/main/java/com/sysone/ddogdog/common/config/AuthenticattorFilter.java
  src/main/java/com/sysone/ddogdog/common/config/CustomAccessDeniedHandler.java
  src/main/java/com/sysone/ddogdog/common/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/common/config/form/CustomDetailService.java
  src/main/java/com/sysone/ddogdog/common/config/form/CustomDetails.java
  src/main/java/com/sysone/ddogdog/common/config/form/CustomLoginFailureHandler.java
  src/main/java/com/sysone/ddogdog/common/config/form/CustomLoginSuccessHandler.java
  src/main/java/com/sysone/ddogdog/common/controller/CommonController.java
  src/main/java/com/sysone/ddogdog/owner/auth/controller/AuthController.java
  src/main/java/com/sysone/ddogdog/owner/auth/repository/AuthMapper.java
  src/main/java/com/sysone/ddogdog/owner/user/controller/UserController.java
  src/main/resources/mapper/owner/auth.xml
  src/main/resources/static/js/owners/auth.js
  src/main/resources/static/js/owners/main.js
  src/main/webapp/WEB-INF/views/owner/index.jsp
  src/main/webapp/WEB-INF/views/owner/login.jsp
  src/main/webapp/WEB-INF/views/owner/mypage.jsp
  src/main/webapp/WEB-INF/views/owner/signUp.jsp
Labels: 기능, 리팩터링, 백엔드

#21 [Feature] 견주 회원가입 및 로그인 Security 활용하여 구현 및 Security 설정
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/KakaoUserInfo.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/OAuth2UserInfo.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/PrincipalDetails.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/PrincipalOauth2UserService.java
  src/main/java/com/sysone/ddogdog/customer/auth/controller/AuthController.java
  src/main/java/com/sysone/ddogdog/customer/auth/controller/KakaoController.java
  src/main/java/com/sysone/ddogdog/customer/auth/mapper/AuthMapper.xml
  src/main/java/com/sysone/ddogdog/customer/auth/mapper/KakaoMapper.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/AddressCustomerDTO.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/AddressDTO.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/KakaoProfile.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/OAuthUser.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/User.java
  src/main/java/com/sysone/ddogdog/customer/auth/service/AuthService.java
  src/main/java/com/sysone/ddogdog/customer/auth/service/KakaoService.java
  src/main/resources/mapper/customer/auth/kakaoMapper.xml
  src/main/resources/static/js/customers/location.js
  src/main/webapp/WEB-INF/views/customer/auth/home.jsp
  src/main/webapp/WEB-INF/views/customer/auth/location.jsp
  src/main/webapp/WEB-INF/views/customer/auth/login.jsp
Labels: 기능, 프론트엔드, 리팩터링, 백엔드

#24 [Feature] S3 설정 및 이미지 업로드,삭제 API 구현
  build.gradle
  src/main/java/com/sysone/ddogdog/common/config/S3Config.java
  src/main/java/com/sysone/ddogdog/common/config/s3/Exception/ErrorCode.java
  src/main/java/com/sysone/ddogdog/common/config/s3/Exception/S3Exception.java
  src/main/java/com/sysone/ddogdog/common/config/s3/controller/S3ImageController.java
  src/main/java/com/sysone/ddogdog/common/config/s3/controller/S3ImageViewController.java
  src/main/java/com/sysone/ddogdog/common/config/s3/service/S3ImageService.java
  src/main/resources/application.yml
  src/main/resources/static/js/common/s3/testPage.js
  src/main/webapp/WEB-INF/views/common/s3/testPage.jsp
Labels: 프로젝트 세팅, 기능, 백엔드

#25 [Feature] 메인 랜딩 페이지 제작
  src/main/java/com/sysone/ddogdog/common/controller/CommonController.java
  src/main/resources/static/css/common/index.css
  src/main/resources/static/font/JalnanGothicTTF.ttf
  src/main/resources/static/img/common/dogs.jpg
  src/main/resources/static/img/common/first.png
  src/main/resources/static/img/common/four.jpg
  src/main/resources/static/img/common/second.png
  src/main/resources/static/img/common/third.png
  src/main/resources/static/js/common/index.js
  src/main/webapp/WEB-INF/views/common/index.jsp
Labels: 기능, 프론트엔드, 디자인

#27 [Feature] 검색 결과 페이지 구현
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/Hotel.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/HotelVO.java
  src/main/resources/mapper/customer/hotel.xml
  src/main/resources/static/css/customers/common.css
  src/main/resources/static/css/customers/header.css
  src/main/resources/static/css/customers/hotel.css
  src/main/resources/static/css/customers/index.css
  src/main/resources/static/img/cancel.svg
  src/main/resources/static/js/customers/dateHandler.js
  src/main/resources/static/js/customers/hotel.js
  src/main/resources/static/js/customers/index.js
  src/main/webapp/WEB-INF/views/customer/hotel.jsp
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 기능, 프론트엔드, 리팩터링, 백엔드

#29 [Feature] ONWER 메인페이지 화면 구현
  build.gradle
  src/main/resources/static/css/owners/footer.css
  src/main/resources/static/css/owners/header.css
  src/main/resources/static/css/owners/index.css
  src/main/resources/static/css/owners/owners.css
  src/main/resources/static/img/owner/customerMain.png
  src/main/resources/static/img/owner/hotelSearch.png
  src/main/resources/static/js/owners/header.js
  src/main/resources/static/js/owners/index.js
  src/main/webapp/WEB-INF/views/owner/component/footer.jsp
  src/main/webapp/WEB-INF/views/owner/component/header.jsp
  src/main/webapp/WEB-INF/views/owner/index.jsp
  src/main/webapp/WEB-INF/views/owner/login.jsp
  src/main/webapp/WEB-INF/views/owner/mypage.jsp
  src/main/webapp/WEB-INF/views/owner/signUp.jsp
Labels: 프론트엔드, 디자인

#31 [Feature] 마이페이지. 인증/인가 리팩토링 적용
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/PrincipalDetails.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/PrincipalOauth2UserService.java
  src/main/java/com/sysone/ddogdog/customer/auth/controller/KakaoController.java
  src/main/java/com/sysone/ddogdog/customer/auth/mapper/KakaoMapper.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/CustomerDTO.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/User.java
  src/main/java/com/sysone/ddogdog/customer/auth/service/KakaoService.java
  src/main/java/com/sysone/ddogdog/customer/common/util/OAuthDataConverter.java
  src/main/java/com/sysone/ddogdog/customer/member/controller/MemberController.java
  src/main/java/com/sysone/ddogdog/customer/member/controller/MemberViewController.java
  src/main/java/com/sysone/ddogdog/customer/member/mapper/MemberMapper.java
  src/main/java/com/sysone/ddogdog/customer/member/service/MemberService.java
  src/main/java/com/sysone/ddogdog/customer/pet/controller/PetViewController.java
  src/main/resources/mapper/customer/auth/kakaoMapper.xml
  src/main/resources/mapper/customer/member/memberMapper.xml
  src/main/resources/static/css/customers/header.css
  src/main/resources/static/css/customers/myPage.css
  src/main/resources/static/img/kakao_login_medium.png
  src/main/resources/static/img/kakaologo.png
  src/main/resources/static/js/customers/myPage.js
  src/main/webapp/WEB-INF/views/common/index.jsp
  src/main/webapp/WEB-INF/views/customer/auth/home.jsp
  src/main/webapp/WEB-INF/views/customer/component/header.jsp
  src/main/webapp/WEB-INF/views/customer/myPage.jsp
  src/main/webapp/WEB-INF/views/customer/petAdd.jsp
  src/main/webapp/WEB-INF/views/customer/pets.jsp
Labels: 기능, 프론트엔드, 리팩터링, 백엔드

#34 [Feature] OWNER 호텔 등록 api 개발
  src/main/java/com/sysone/ddogdog/common/address/model/AddressDTO.java
  src/main/java/com/sysone/ddogdog/common/address/repository/AddressMapper.java
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/common/config/form/CustomLoginSuccessHandler.java
  src/main/java/com/sysone/ddogdog/owner/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/owner/hotel/model/HotelDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/model/RequestHotelDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/repository/OwnerHotelMapper.java
  src/main/java/com/sysone/ddogdog/owner/hotel/service/OwnerHotelService.java
  src/main/java/com/sysone/ddogdog/owner/user/controller/UserController.java
  src/main/resources/mapper/common/address/address.xml
  src/main/resources/mapper/owner/hotel.xml
  src/main/resources/static/css/owners/header.css
  src/main/resources/static/css/owners/hotelRegister.css
  src/main/resources/static/css/owners/index.css
  src/main/resources/static/js/owners/header.js
  src/main/resources/static/js/owners/hotelRegister.js
  src/main/webapp/WEB-INF/views/owner/component/header.jsp
  src/main/webapp/WEB-INF/views/owner/hotelRegister.jsp
  src/main/webapp/WEB-INF/views/owner/login.jsp
  src/main/webapp/WEB-INF/views/owner/signUp.jsp
Labels: 기능, 리팩터링, 백엔드

#36 [Refactor] 날짜 기반 검색 기능 구현
  src/main/java/com/sysone/ddogdog/common/controller/CommonController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/mapper/HotelMapper.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/HotelDTO.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/HotelVO.java
  src/main/java/com/sysone/ddogdog/customer/hotel/service/HotelService.java
  src/main/resources/mapper/customer/hotel.xml
  src/main/resources/static/js/customers/index.js
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 기능, 프론트엔드, 리팩터링, 백엔드

#38 [Feature] Role에 따른 로그아웃 설정
  src/main/java/com/sysone/ddogdog/common/config/CustomLogoutSuccessHandler.java
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/resources/mapper/customer/hotel.xml
  src/main/webapp/WEB-INF/views/customer/component/header.jsp
  src/main/webapp/WEB-INF/views/owner/component/header.jsp
Labels: 기능, 리팩터링, 백엔드

#40 [Feature]Owner 호텔 객실 등록 API 생성
  src/main/java/com/sysone/ddogdog/owner/hotel/model/HotelDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/service/OwnerHotelService.java
  src/main/java/com/sysone/ddogdog/owner/room/controller/RoomController.java
  src/main/java/com/sysone/ddogdog/owner/room/mapper/RoomMapper.java
  src/main/java/com/sysone/ddogdog/owner/room/model/RequestRoomDTO.java
  src/main/java/com/sysone/ddogdog/owner/room/model/RoomDTO.java
  src/main/java/com/sysone/ddogdog/owner/room/model/RoomGrade.java
  src/main/java/com/sysone/ddogdog/owner/room/service/RoomService.java
  src/main/resources/mapper/owner/room.xml
  src/main/resources/static/css/owners/roomRegister.css
  src/main/resources/static/js/owners/RoomRegister.js
  src/main/webapp/WEB-INF/views/owner/roomRegister.jsp
Labels: 기능, 백엔드

#42 [Feature] 펫 추가, 펫 조회 기능 구현
  src/main/java/com/sysone/ddogdog/customer/pet/controller/PetController.java
  src/main/java/com/sysone/ddogdog/customer/pet/controller/PetViewController.java
  src/main/java/com/sysone/ddogdog/customer/pet/mapper/PetMapper.java
  src/main/java/com/sysone/ddogdog/customer/pet/model/PetDTO.java
  src/main/java/com/sysone/ddogdog/customer/pet/model/PetSpeciesDTO.java
  src/main/java/com/sysone/ddogdog/customer/pet/model/RequestPetDTO.java
  src/main/java/com/sysone/ddogdog/customer/pet/service/PetService.java
  src/main/resources/mapper/customer/pet/petMapper.xml
  src/main/resources/static/css/customers/petAdd.css
  src/main/resources/static/css/customers/pets.css
  src/main/resources/static/img/memo2.PNG
  src/main/resources/static/js/customers/location.js
  src/main/resources/static/js/customers/petAdd.js
  src/main/resources/static/js/customers/pets.js
  src/main/webapp/WEB-INF/views/customer/petAdd.jsp
  src/main/webapp/WEB-INF/views/customer/petDetails.jsp
  src/main/webapp/WEB-INF/views/customer/pets.jsp
Labels: 기능, 프론트엔드, 백엔드

#46 [Feature] OWNER 호텔 관리 목록 및 객실관리 목록 조회 API 생성
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/owner/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/owner/hotel/mapper/OwnerHotelMapper.java
  src/main/java/com/sysone/ddogdog/owner/hotel/model/ResponseHotelDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/repository/OwnerHotelMapper.java
  src/main/java/com/sysone/ddogdog/owner/hotel/service/OwnerHotelService.java
  src/main/java/com/sysone/ddogdog/owner/room/controller/RoomController.java
  src/main/java/com/sysone/ddogdog/owner/room/mapper/RoomMapper.java
  src/main/java/com/sysone/ddogdog/owner/room/model/ResponseRoomDTO.java
  src/main/java/com/sysone/ddogdog/owner/room/model/RoomVO.java
  src/main/java/com/sysone/ddogdog/owner/room/service/RoomService.java
  src/main/resources/mapper/owner/hotel.xml
  src/main/resources/mapper/owner/room.xml
  src/main/resources/static/css/owners/hotelList.css
  src/main/resources/static/css/owners/login.css
  src/main/resources/static/css/owners/roomList.css
  src/main/resources/static/css/owners/roomRegister.css
  src/main/resources/static/css/owners/signUp.css
  src/main/resources/static/js/owners/RoomRegister.js
  src/main/resources/static/js/owners/hotelList.js
  src/main/resources/static/js/owners/hotelRegister.js
  src/main/resources/static/js/owners/roomlList.js
  src/main/resources/static/js/owners/signUp.js
  src/main/webapp/WEB-INF/views/owner/component/header.jsp
  src/main/webapp/WEB-INF/views/owner/hotelList.jsp
  src/main/webapp/WEB-INF/views/owner/login.jsp
  src/main/webapp/WEB-INF/views/owner/roomList.jsp
  src/main/webapp/WEB-INF/views/owner/roomRegister.jsp
  src/main/webapp/WEB-INF/views/owner/signUp.jsp
Labels: 기능, 리팩터링, 백엔드

#48 [Feature] 호텔 상세 조회 구현
  src/main/java/com/sysone/ddogdog/common/controller/CommonController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/mapper/HotelMapper.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/HotelVO.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/ResponseHotelDTO.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/ResponseHotelDetailsDTO.java
  src/main/java/com/sysone/ddogdog/customer/hotel/service/HotelService.java
  src/main/java/com/sysone/ddogdog/customer/room/mapper/RoomMapper.java
  src/main/java/com/sysone/ddogdog/customer/room/model/ResponseRoomDTO.java
  src/main/java/com/sysone/ddogdog/customer/room/model/RoomDTO.java
  src/main/java/com/sysone/ddogdog/customer/room/model/RoomGrade.java
  src/main/resources/mapper/customer/hotel/hotel.xml
  src/main/resources/mapper/customer/room/room.xml
  src/main/resources/static/css/customers/index.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/js/customers/index.js
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 기능, 리팩터링, 백엔드, 버그 처리

#50 [Fix] mapping 문제 해결
  src/main/resources/mapper/customer/hotel/hotel.xml
Labels: 버그, 버그 처리

#52 [Feature] 예약, 방선택 기능 구현
  src/main/java/com/sysone/ddogdog/customer/common/util/BooleanTypeHandler.java
  src/main/java/com/sysone/ddogdog/customer/common/util/CommonUtils.java
  src/main/java/com/sysone/ddogdog/customer/common/util/LocalDateTypeHandler.java
  src/main/java/com/sysone/ddogdog/customer/reservation/controller/ReservationController.java
  src/main/java/com/sysone/ddogdog/customer/reservation/mapper/ReservationMapper.java
  src/main/java/com/sysone/ddogdog/customer/reservation/model/RequsetReservationDTO.java
  src/main/java/com/sysone/ddogdog/customer/reservation/model/Reservation.java
  src/main/java/com/sysone/ddogdog/customer/reservation/service/ReservationService.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/exception/NoAvailableRoomsException.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/mapper/RoomChoiceMapper.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/model/RequestRoomChoiceDTO.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/model/RoomChoice.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/service/RoomChoiceService.java
  src/main/resources/mapper/customer/reservation/reservationMapper.xml
  src/main/resources/mapper/customer/roomChoice/roomChoiceMapper.xml
Labels: 기능, 백엔드

#54 [Feature] OWNER 호텔 정보 및 객실 정보 수정 API 생성
  src/main/java/com/sysone/ddogdog/common/address/repository/AddressMapper.java
  src/main/java/com/sysone/ddogdog/owner/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/owner/hotel/mapper/OwnerHotelMapper.java
  src/main/java/com/sysone/ddogdog/owner/hotel/model/HotelDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/model/ResponseHotelDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/service/OwnerHotelService.java
  src/main/java/com/sysone/ddogdog/owner/room/controller/RoomController.java
  src/main/java/com/sysone/ddogdog/owner/room/mapper/OwnerRoomMapper.java
  src/main/java/com/sysone/ddogdog/owner/room/mapper/RoomMapper.java
  src/main/java/com/sysone/ddogdog/owner/room/model/ResponseRoomDTO.java
  src/main/java/com/sysone/ddogdog/owner/room/model/RoomDTO.java
  src/main/java/com/sysone/ddogdog/owner/room/model/RoomVO.java
  src/main/java/com/sysone/ddogdog/owner/room/service/RoomService.java
  src/main/resources/mapper/common/address/address.xml
  src/main/resources/mapper/owner/hotel.xml
  src/main/resources/mapper/owner/room.xml
  src/main/resources/static/css/owners/updateHotel.css
  src/main/resources/static/css/owners/updateRoom.css
  src/main/resources/static/js/owners/updateHotel.js
  src/main/resources/static/js/owners/updateRoom.js
  src/main/webapp/WEB-INF/views/owner/hotelList.jsp
  src/main/webapp/WEB-INF/views/owner/roomList.jsp
  src/main/webapp/WEB-INF/views/owner/updateHotel.jsp
  src/main/webapp/WEB-INF/views/owner/updateRoom.jsp
Labels: 기능, 리팩터링, 백엔드

#58 [Feature] 견주 호텔 예약 페이지 구현
  src/main/java/com/sysone/ddogdog/common/address/repository/AddressMapper.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/ResponseHotelDetailsDTO.java
  src/main/java/com/sysone/ddogdog/customer/hotel/service/HotelService.java
  src/main/resources/mapper/common/address/address.xml
  src/main/resources/static/css/customers/hotelDetail.css
  src/main/resources/static/js/customers/hotelDetail.js
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
Labels: 기능, 프론트엔드, 리팩터링

#60 [Feature] 견주 예약 목록 확인, 예약 취소, 객실 정보 조회 API, 화면 구현
  src/main/java/com/sysone/ddogdog/common/address/repository/AddressMapper.java
  src/main/java/com/sysone/ddogdog/customer/reservation/controller/ReservationController.java
  src/main/java/com/sysone/ddogdog/customer/reservation/controller/ReservationViewController.java
  src/main/java/com/sysone/ddogdog/customer/reservation/mapper/ReservationMapper.java
  src/main/java/com/sysone/ddogdog/customer/reservation/model/RequestReservationDTO.java
  src/main/java/com/sysone/ddogdog/customer/reservation/model/Reservation.java
  src/main/java/com/sysone/ddogdog/customer/reservation/model/ResponseReservationDTO.java
  src/main/java/com/sysone/ddogdog/customer/reservation/service/ReservationService.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/controller/RoomChoiceController.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/mapper/RoomChoiceMapper.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/model/RequestRoomChoiceDTO.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/model/ResponseRoomChoiceDTO.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/service/RoomChoiceService.java
  src/main/resources/application.yml
  src/main/resources/mapper/common/address/address.xml
  src/main/resources/mapper/customer/reservation/reservationMapper.xml
  src/main/resources/mapper/customer/roomChoice/roomChoiceMapper.xml
  src/main/resources/static/css/customers/header.css
  src/main/resources/static/css/customers/pets.css
  src/main/resources/static/css/customers/reservationInfo.css
  src/main/resources/static/js/customers/hotelDetail.js
  src/main/resources/static/js/customers/myPage.js
  src/main/resources/static/js/customers/reservationInfo.js
  src/main/webapp/WEB-INF/views/customer/component/header.jsp
  src/main/webapp/WEB-INF/views/customer/myPage.jsp
  src/main/webapp/WEB-INF/views/customer/pets.jsp
  src/main/webapp/WEB-INF/views/customer/reservationInfo.jsp
Labels: 기능, 프론트엔드, 리팩터링, 백엔드

#62 [Feature] 월별 일별 예약 조회 API 생성
  src/main/java/com/sysone/ddogdog/owner/auth/controller/AuthController.java
  src/main/java/com/sysone/ddogdog/owner/auth/controller/AuthViewController.java
  src/main/java/com/sysone/ddogdog/owner/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/owner/hotel/controller/HotelViewController.java
  src/main/java/com/sysone/ddogdog/owner/reservation/controller/ReservationViewController.java
  src/main/java/com/sysone/ddogdog/owner/reservation/mapper/OwnerReservationMapper.java
  src/main/java/com/sysone/ddogdog/owner/reservation/model/ReservationDTO.java
  src/main/java/com/sysone/ddogdog/owner/reservation/model/ResponseReservationDayDTO.java
  src/main/java/com/sysone/ddogdog/owner/reservation/model/ResponseReservationMonthDTO.java
  src/main/java/com/sysone/ddogdog/owner/reservation/service/OwnerReservationService.java
  src/main/java/com/sysone/ddogdog/owner/room/controller/RoomController.java
  src/main/java/com/sysone/ddogdog/owner/room/controller/RoomViewController.java
  src/main/java/com/sysone/ddogdog/owner/room/mapper/OwnerRoomMapper.java
  src/main/java/com/sysone/ddogdog/owner/room/model/RoomGrade.java
  src/main/java/com/sysone/ddogdog/owner/room/service/RoomService.java
  src/main/resources/mapper/owner/reservation.xml
  src/main/resources/mapper/owner/room.xml
  src/main/webapp/WEB-INF/views/owner/dayReservation.jsp
  src/main/webapp/WEB-INF/views/owner/monthReservation.jsp
  src/main/webapp/WEB-INF/views/owner/roomRegister.jsp
Labels: 기능, 리팩터링, 백엔드

#67 [Refactor] 고객 페이지 header, footer 수정
  src/main/resources/static/css/customers/footer.css
  src/main/resources/static/css/customers/header.css
  src/main/resources/static/img/footer_img.svg
  src/main/webapp/WEB-INF/views/customer/component/footer.jsp
  src/main/webapp/WEB-INF/views/customer/component/header.jsp
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 프론트엔드, 디자인, 리팩터링

#69 [Feature] 예약관리 프론트 페이지 작성
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/owner/reservation/controller/ReservationController.java
  src/main/java/com/sysone/ddogdog/owner/reservation/controller/ReservationViewController.java
  src/main/java/com/sysone/ddogdog/owner/reservation/service/OwnerReservationService.java
  src/main/resources/mapper/owner/reservation.xml
  src/main/resources/static/css/owners/reservation.css
  src/main/resources/static/js/owners/reservation.js
  src/main/resources/static/js/owners/roomRegister.js
  src/main/webapp/WEB-INF/views/owner/component/header.jsp
  src/main/webapp/WEB-INF/views/owner/dayReservation.jsp
  src/main/webapp/WEB-INF/views/owner/monthReservation.jsp
  src/main/webapp/WEB-INF/views/owner/reservation.jsp
Labels: 기능, 프론트엔드, 리팩터링

#71 [Refactor] 고객 호텔 상세 페이지 UI 수정
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelController.java
  src/main/resources/static/css/customers/common.css
  src/main/resources/static/css/customers/header.css
  src/main/resources/static/css/customers/hotelDetail.css
  src/main/resources/static/css/customers/index.css
  src/main/resources/static/js/customers/hotelDetail.js
  src/main/resources/static/js/customers/index.js
  src/main/resources/static/js/customers/locationHandler.js
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 프론트엔드, 디자인, 리팩터링

#75 [Feature] Owner 연매출 통계 페이지 작성
  src/main/java/com/sysone/ddogdog/owner/reservation/controller/ReservationController.java
  src/main/java/com/sysone/ddogdog/owner/reservation/controller/ReservationViewController.java
  src/main/java/com/sysone/ddogdog/owner/reservation/mapper/OwnerReservationMapper.java
  src/main/java/com/sysone/ddogdog/owner/reservation/model/ResponseReservationYearDTO.java
  src/main/java/com/sysone/ddogdog/owner/reservation/service/OwnerReservationService.java
  src/main/resources/mapper/owner/reservation.xml
  src/main/resources/static/css/owners/statistics.css
  src/main/resources/static/js/owners/statistics.js
  src/main/webapp/WEB-INF/views/owner/statistics.jsp
Labels: 기능, 프론트엔드, 백엔드

#78 [Refactor] owner 메인 페이지 UI 수정
  src/main/resources/static/css/customers/header.css
  src/main/resources/static/css/owners/common.css
  src/main/resources/static/css/owners/footer.css
  src/main/resources/static/css/owners/header.css
  src/main/resources/static/css/owners/index.css
  src/main/resources/static/img/owner/corgi.svg
  src/main/resources/static/img/owner/logo_nobg.svg
  src/main/resources/static/img/owner/main1.svg
  src/main/resources/static/img/owner/main2.svg
  src/main/resources/static/img/owner/main3.svg
  src/main/resources/static/js/customers/header.js
  src/main/resources/static/js/owners/header.js
  src/main/resources/static/js/owners/index.js
  src/main/webapp/WEB-INF/views/customer/component/header.jsp
  src/main/webapp/WEB-INF/views/owner/component/footer.jsp
  src/main/webapp/WEB-INF/views/owner/component/header.jsp
  src/main/webapp/WEB-INF/views/owner/index.jsp
Labels: 프론트엔드, 디자인, 리팩터링

#80 [Feature ] 펫 추가, 수정 UI 개선
  src/main/resources/mapper/customer/reservation/reservationMapper.xml
  src/main/resources/static/css/customers/common.css
  src/main/resources/static/css/customers/petAdd.css
  src/main/resources/static/css/customers/reservationInfo.css
  src/main/resources/static/img/bookbg.PNG
  src/main/resources/static/js/customers/petAdd.js
  src/main/resources/static/js/customers/petDetails.js
  src/main/resources/static/js/customers/reservationInfo.js
  src/main/webapp/WEB-INF/views/customer/petAdd.jsp
  src/main/webapp/WEB-INF/views/customer/petDetails.jsp
Labels: 디자인, 리팩터링

#82 [Refactor] Owner 로그인 회원가입 및 예약관리 페이지 UI 적용
  src/main/java/com/sysone/ddogdog/common/config/form/CustomDetails.java
  src/main/resources/static/css/owners/common.css
  src/main/resources/static/css/owners/header.css
  src/main/resources/static/css/owners/hotelList.css
  src/main/resources/static/css/owners/hotelRegister.css
  src/main/resources/static/css/owners/index.css
  src/main/resources/static/css/owners/login.css
  src/main/resources/static/css/owners/reservation.css
  src/main/resources/static/css/owners/roomList.css
  src/main/resources/static/css/owners/roomRegister.css
  src/main/resources/static/css/owners/signUp.css
  src/main/resources/static/css/owners/statistics.css
  src/main/resources/static/css/owners/updateHotel.css
  src/main/resources/static/css/owners/updateRoom.css
  src/main/resources/static/js/owners/hotelRegister.js
  src/main/resources/static/js/owners/reservation.js
  src/main/resources/static/js/owners/roomRegister.js
  src/main/webapp/WEB-INF/views/owner/component/header.jsp
  src/main/webapp/WEB-INF/views/owner/hotelList.jsp
  src/main/webapp/WEB-INF/views/owner/hotelRegister.jsp
  src/main/webapp/WEB-INF/views/owner/index.jsp
  src/main/webapp/WEB-INF/views/owner/login.jsp
  src/main/webapp/WEB-INF/views/owner/mypage.jsp
  src/main/webapp/WEB-INF/views/owner/reservation.jsp
  src/main/webapp/WEB-INF/views/owner/roomList.jsp
  src/main/webapp/WEB-INF/views/owner/roomRegister.jsp
  src/main/webapp/WEB-INF/views/owner/signUp.jsp
  src/main/webapp/WEB-INF/views/owner/statistics.jsp
  src/main/webapp/WEB-INF/views/owner/updateHotel.jsp
  src/main/webapp/WEB-INF/views/owner/updateRoom.jsp
Labels: 디자인, 리팩터링

#83 [Feature] 고객 페이지 검색 자동완성구현
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelViewController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/mapper/HotelMapper.java
  src/main/java/com/sysone/ddogdog/customer/hotel/service/HotelService.java
  src/main/resources/mapper/customer/hotel/hotel.xml
  src/main/resources/static/css/customers/common.css
  src/main/resources/static/css/customers/index.css
  src/main/resources/static/js/customers/hotel.js
  src/main/resources/static/js/customers/searchAutocomplete.js
  src/main/webapp/WEB-INF/views/customer/hotel.jsp
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 기능, 프론트엔드, 백엔드

#86 [Feature] Github Action 을 위한 workflow 작성
  .github/workflows/ddogdog-workflow.yml
Labels: 인프라

#87 [Feature] 자바 메일을 활용한 예약 이메일 발송 기능 구현
  Dockerfile
  build.gradle
  src/main/java/com/sysone/ddogdog/common/config/MailConfig.java
  src/main/java/com/sysone/ddogdog/common/config/mail/model/RequestEmailContentDTO.java
  src/main/java/com/sysone/ddogdog/common/config/mail/service/EmailService.java
  src/main/java/com/sysone/ddogdog/common/controller/HealthCheckController.java
  src/main/java/com/sysone/ddogdog/customer/reservation/controller/ReservationController.java
  src/main/java/com/sysone/ddogdog/customer/reservation/service/ReservationService.java
  src/main/resources/application.yml
Labels: 기능, 인프라, 백엔드

#92 [Refactor] 검색 페이지 ui 수정
  src/main/resources/static/css/customers/hotel.css
  src/main/resources/static/css/customers/hotelDetail.css
  src/main/resources/static/js/customers/hotel.js
  src/main/resources/static/js/customers/hotelDetail.js
  src/main/resources/static/js/customers/index.js
  src/main/resources/static/js/customers/searchAutocomplete.js
  src/main/webapp/WEB-INF/views/customer/hotel.jsp
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 프론트엔드, 디자인, 리팩터링

#94 [Feature] 호텔 리스트 페이지네이션 api 구현
  build.gradle
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelViewController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/service/HotelService.java
Labels: 기능, 백엔드

#96 [Refactor] 예약 내역 페이지 UI 수정
  src/main/resources/static/css/customers/reservationInfo.css
  src/main/resources/static/js/customers/hotelDetail.js
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
  src/main/webapp/WEB-INF/views/customer/reservationInfo.jsp
Labels: 프론트엔드, 디자인

#97 [Refactor] 호텔 관리 및 통계 페이지 UI 수정
  src/main/resources/static/css/owners/common.css
  src/main/resources/static/css/owners/hotelList.css
  src/main/resources/static/css/owners/hotelRegister.css
  src/main/resources/static/css/owners/roomList.css
  src/main/resources/static/css/owners/roomRegister.css
  src/main/resources/static/css/owners/signUp.css
  src/main/resources/static/css/owners/statistics.css
  src/main/resources/static/css/owners/updateHotel.css
  src/main/resources/static/css/owners/updateRoom.css
  src/main/resources/static/js/owners/hotelRegister.js
  src/main/resources/static/js/owners/roomRegister.js
  src/main/resources/static/js/owners/statistics.js
  src/main/resources/static/js/owners/updateHotel.js
  src/main/resources/static/js/owners/updateRoom.js
  src/main/webapp/WEB-INF/views/owner/hotelList.jsp
  src/main/webapp/WEB-INF/views/owner/hotelRegister.jsp
  src/main/webapp/WEB-INF/views/owner/index.jsp
  src/main/webapp/WEB-INF/views/owner/mypage.jsp
  src/main/webapp/WEB-INF/views/owner/reservation.jsp
  src/main/webapp/WEB-INF/views/owner/roomList.jsp
  src/main/webapp/WEB-INF/views/owner/roomRegister.jsp
  src/main/webapp/WEB-INF/views/owner/signUp.jsp
  src/main/webapp/WEB-INF/views/owner/statistics.jsp
  src/main/webapp/WEB-INF/views/owner/updateHotel.jsp
  src/main/webapp/WEB-INF/views/owner/updateRoom.jsp
Labels: 디자인, 리팩터링

#99 [Feature] 펫 수정 기능 리팩토링, 예약 내역 조회 페이지네이션 적용
  src/main/java/com/sysone/ddogdog/customer/pet/controller/PetController.java
  src/main/java/com/sysone/ddogdog/customer/pet/service/PetService.java
  src/main/java/com/sysone/ddogdog/customer/reservation/controller/ReservationViewController.java
  src/main/java/com/sysone/ddogdog/customer/reservation/mapper/ReservationMapper.java
  src/main/java/com/sysone/ddogdog/customer/reservation/service/ReservationService.java
  src/main/resources/mapper/customer/reservation/reservationMapper.xml
  src/main/resources/static/css/customers/petAdd.css
  src/main/resources/static/js/customers/petAdd.js
  src/main/resources/static/js/customers/petDetails.js
  src/main/webapp/WEB-INF/views/customer/petDetails.jsp
Labels: 기능, 프론트엔드, 리팩터링, 백엔드

#102 [Feature] 호텔 리스트, 예약 내역 페이지네이션
  src/main/resources/static/css/customers/common.css
  src/main/resources/static/css/customers/header.css
  src/main/resources/static/css/customers/hotel.css
  src/main/resources/static/css/customers/hotelDetail.css
  src/main/resources/static/css/customers/index.css
  src/main/resources/static/css/customers/reservationInfo.css
  src/main/resources/static/img/stamp.svg
  src/main/resources/static/js/customers/hotel.js
  src/main/resources/static/js/customers/index.js
  src/main/resources/static/js/customers/location.js
  src/main/webapp/WEB-INF/views/customer/hotel.jsp
  src/main/webapp/WEB-INF/views/customer/reservationInfo.jsp
Labels: 기능, 프론트엔드, 디자인

#103 [Refactro]호텔 정보 수정 주소 업데이트 변경 및 DTO 어노테이션 변경
  src/main/java/com/sysone/ddogdog/common/address/model/AddressDTO.java
  src/main/java/com/sysone/ddogdog/common/address/repository/AddressMapper.java
  src/main/java/com/sysone/ddogdog/owner/auth/model/AuthDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/model/HotelDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/model/ResponseHotelDTO.java
  src/main/java/com/sysone/ddogdog/owner/hotel/service/OwnerHotelService.java
  src/main/java/com/sysone/ddogdog/owner/reservation/model/ReservationDTO.java
  src/main/java/com/sysone/ddogdog/owner/room/model/RoomDTO.java
  src/main/resources/mapper/common/address/address.xml
  src/main/resources/mapper/owner/hotel.xml
  src/main/resources/static/css/owners/hotelList.css
  src/main/resources/static/css/owners/reservation.css
  src/main/resources/static/css/owners/roomList.css
  src/main/resources/static/css/owners/updateHotel.css
  src/main/resources/static/css/owners/updateRoom.css
  src/main/resources/static/js/owners/hotelList.js
  src/main/resources/static/js/owners/hotelRegister.js
  src/main/resources/static/js/owners/roomRegister.js
  src/main/resources/static/js/owners/roomlList.js
  src/main/resources/static/js/owners/signUp.js
  src/main/resources/static/js/owners/statistics.js
  src/main/resources/static/js/owners/updateHotel.js
  src/main/resources/static/js/owners/updateRoom.js
  src/main/webapp/WEB-INF/views/owner/hotelRegister.jsp
  src/main/webapp/WEB-INF/views/owner/roomRegister.jsp
  src/main/webapp/WEB-INF/views/owner/signUp.jsp
  src/main/webapp/WEB-INF/views/owner/updateHotel.jsp
  src/main/webapp/WEB-INF/views/owner/updateRoom.jsp
Labels: 기능, 프론트엔드, 디자인, 리팩터링, 백엔드

#104 [Refactor] 카카오 로그아웃 경로 변경, 예외처리 리팩토링
  src/main/java/com/sysone/ddogdog/common/config/CustomLogoutSuccessHandler.java
  src/main/java/com/sysone/ddogdog/common/config/mail/service/EmailService.java
  src/main/java/com/sysone/ddogdog/common/config/s3/service/S3ImageService.java
  src/main/java/com/sysone/ddogdog/common/controller/CommonController.java
  src/main/java/com/sysone/ddogdog/common/exception/CommonErrorCode.java
  src/main/java/com/sysone/ddogdog/common/exception/CustomerErrorCode.java
  src/main/java/com/sysone/ddogdog/common/exception/GlobalExceptionErrorPageHandler.java
  src/main/java/com/sysone/ddogdog/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sysone/ddogdog/common/exception/NoAvailableRoomsException.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/request/requestDTO.java
  src/main/java/com/sysone/ddogdog/customer/auth/model/response/responseDTO.java
  src/main/java/com/sysone/ddogdog/customer/hotel/model/HotelDTO.java
  src/main/java/com/sysone/ddogdog/customer/reservation/controller/ReservationController.java
  src/main/java/com/sysone/ddogdog/customer/reservation/model/Reservation.java
  src/main/java/com/sysone/ddogdog/customer/room/model/RoomDTO.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/exception/NoAvailableRoomsException.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/model/RoomChoice.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/service/RoomChoiceService.java
  src/main/resources/static/css/error/500.css
  src/main/resources/static/img/500.png
  src/main/resources/static/js/customers/hotelDetail.js
  src/main/webapp/WEB-INF/views/error/404.jsp
  src/main/webapp/WEB-INF/views/error/500.jsp
Labels: 리팩터링, 백엔드

#108 [Refactor] Owner 헤더 로그인 후 이용 알럿 추가 및 시큐리티 필터 추가
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/resources/static/js/owners/header.js
  src/main/webapp/WEB-INF/views/owner/component/header.jsp
Labels: 프론트엔드, 디자인, 리팩터링, 백엔드

#109 [Feature] security 추가 설정 및 동시 세션 제한 처리
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/common/config/oauth/PrincipalDetails.java
  src/main/java/com/sysone/ddogdog/customer/auth/controller/KakaoController.java
  src/main/java/com/sysone/ddogdog/customer/auth/controller/KakaoViewController.java
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelController.java
  src/main/java/com/sysone/ddogdog/customer/reservation/controller/ReservationController.java
  src/main/java/com/sysone/ddogdog/customer/roomChoice/controller/RoomChoiceController.java
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
Labels: 리팩터링, 백엔드

#111 [Refactor] 세션 설정 추가 및 불필요 파일 삭제
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
  src/main/java/com/sysone/ddogdog/common/config/form/CustomDetails.java
  src/main/webapp/WEB-INF/views/owner/hotelList.jsp
  src/main/webapp/WEB-INF/views/owner/login.jsp
  src/main/webapp/WEB-INF/views/owner/roomList.jsp
Labels: 리팩터링, 백엔드

#112 [Feature] 세션 만료 후 핸들러 적용
  src/main/java/com/sysone/ddogdog/common/config/CustomExpiredSessionStrategy.java
  src/main/java/com/sysone/ddogdog/common/config/SecurityConfig.java
Labels: 기능, 백엔드

#113 [Chore] application.yml S3이미지 용량 증설 설정
  src/main/resources/application.yml
Labels: 기능, 백엔드

#114 Feature/105 customer alert UI
  src/main/java/com/sysone/ddogdog/customer/hotel/service/HotelService.java
  src/main/java/com/sysone/ddogdog/customer/room/model/ResponseRoomDTO.java
  src/main/resources/mapper/customer/hotel/hotel.xml
  src/main/resources/mapper/customer/room/room.xml
  src/main/resources/static/css/common/index.css
  src/main/resources/static/css/customers/hotel.css
  src/main/resources/static/css/customers/index.css
  src/main/resources/static/css/customers/location.css
  src/main/resources/static/img/owner/main1.svg
  src/main/resources/static/img/owner/main2.svg
  src/main/resources/static/img/owner/main3.svg
  src/main/resources/static/js/customers/hotel.js
  src/main/resources/static/js/customers/hotelDetail.js
  src/main/resources/static/js/customers/index.js
  src/main/webapp/WEB-INF/views/common/index.jsp
  src/main/webapp/WEB-INF/views/customer/auth/location.jsp
  src/main/webapp/WEB-INF/views/customer/component/header.jsp
  src/main/webapp/WEB-INF/views/customer/hotel.jsp
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
  src/main/webapp/WEB-INF/views/customer/index.jsp
Labels: 프론트엔드, 디자인, 리팩터링, 백엔드
