Repository Sysone2ndProject/DDogdog, pull requests merged in 2024-10, with the labels that each got.

#115 [Fix] 리디렉션 경로 수정
  src/main/resources/static/js/customers/myPage.js
Labels: 기능, 버그 처리

#116 [Style] css 수정
  src/main/resources/static/css/customers/hotelDetail.css
  src/main/resources/static/css/customers/myPage.css
  src/main/resources/static/js/customers/myPage.js
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
  src/main/webapp/WEB-INF/views/customer/myPage.jsp
  src/main/webapp/WEB-INF/views/owner/hotelList.jsp
  src/main/webapp/WEB-INF/views/owner/roomList.jsp
Labels: 프론트엔드, 디자인

#118 Refactor : 날짜별 방 요청 api 구현, 선택 요일 정상 요청되도록 수정
  src/main/java/com/sysone/ddogdog/customer/hotel/controller/HotelController.java
  src/main/resources/static/css/customers/hotelDetail.css
  src/main/resources/static/js/customers/hotel.js
  src/main/resources/static/js/customers/hotelDetail.js
  src/main/webapp/WEB-INF/views/customer/hotelDetail.jsp
Labels: 기능, 리팩터링
